---
title: "Using Stable Isotopes as Tracers"
author:
  company: "University of Cadiz"
  github: https://github.com/edwardpmorris
  name: "Edward P. Morris"
  twitter: "@EdwardPMorris"
  www: "http://rnm214.uca.es/CV/emorris/cvepmorris"
date: "`r Sys.Date()`"
output:
  ioslides_presentation:
    css: "config/ioslides_ceimar.css"
    logo: "config/UCA-ceimar-logo-480-198-transparent.png"
    template: "config/ioslides_ceimar.html"
---

## Content

+ duration: 3 h teaching session; 1.5 h theory, 1.5 h practice on PC
+ audience: Msc., PhD students and post-docs

## Aims

+ introduce stable isotope tracer techniques
+ provide important terminology specific to tracers
+ give sources of important literature and help
+ give tools for calculations
+ ensure participants can design and analyse stable isotope tracer experiments

## Assessment

+ participation in mini excercises during teaching
+ complete excercises on PC
+ grading of students 1 page 'mock' isotope tracer experiment (optional?)

## Requirements

+ familiarity with general stable isotope terminology (see [lectures]())
+ access to PC with [R](https://cran.r-project.org) and [Rstudio](https://www.rstudio.com/) (try and get Shiny server up and then just a web browser) 
+ a basic idea for a tracer experiment (optional)

## Outline
    
+ When natural abundance is not enough...
    + tracing nutrient cycling
        + biogeocheistry
        + foodwebs
+ Stable isotope specific terminology
+ Where can I find some help?
    + Important literature
    + Forums, groups and software

## Outline

+ How do I calculate that?
    + Basic calculations
    + Using specific software packages
+ My 'first' stable isotope tracer experimental design
    + Setting up the basic calculations
    + Calculating costs
    + Analysing results
